version: "3"
services:
  mongo-service:
    image: mongo
    container_name: database
    environment:
        - MONGO_INITDB_DATABASE=iam-db
        - DATABASE_NAME=iam-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  data-service:
    container_name: grpc
    build: .
    ports:
      - "9090:9090"
    depends_on: [mongo-service]
    tty: true
    environment:
        - DATABASE_URL=mongodb://mongo-service:27017
        - DATABASE_NAME=iam-db