version: "3"
services:
  db:
    image: mongo
    container_name: database
    environment:
        - MONGO_INITDB_DATABASE=iam-db
        - DATABASE_NAME=iam-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  app:
    container_name: grpc
    build: .
    ports:
      - "9090:9090"
    depends_on: [db]
    tty: true
    environment:
        - DATABASE_URL=mongodb://db:27017
        - DATABASE_NAME=iam-db